name: Build and create release
run-name: 
on:
  push:
    branches:
      - "cicd"
  release:
    types: [created]
jobs:
  Build-and-Upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        
      - name: Build Rust Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/subset_sum
          tag: ${{ github.ref }} 
          overwrite: true
          file_glob: true


