name: Run Unit Tests
run-name: 🧪 Running unit tests
on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "develop"
      - "main"
  push:
    branches:
      - "cicd"
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test